# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10@sha256:8caf90f586bf5d313841848ceb4c051ec43b560d8764e82dc2366adc70094f34

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn

      - run:
          name: Build
          command: yarn build

      - run:
          name: Build ecommerce example
          command: |
            yarn examples:ecommerce:build
      - run:
          name: Build router example
          command: |
            yarn examples:router:build
      - run:
          name: Build media example
          command: |
            yarn examples:media:build
      - run:
          name: Build ssr example
          command: |
            yarn examples:ssr:build
      - run:
          name: Test ssr example
          command: |
            yarn examples:ssr:test
      - run:
          name: Build storybook
          command: |
            yarn examples:storybook:build

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      - run:
          name: run CI
          command: yarn test:ci

      - run:
          name: Trigger a release if the latest commit is a release commit
          command: yarn shipjs trigger
